//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class userDetail
    {
        public decimal ID { get; set; }
        public string name { get; set; }
        public Nullable<decimal> age { get; set; }
        public Nullable<decimal> salary { get; set; }
        public string designation { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string last_name { get; set; }
        public string location { get; set; }
    }
}
